'''
Created on Apr 6, 2015

@author: nnair
'''

import re


DEFAULT_NAMES = [
    re.compile('^Abort'),
    re.compile('^Add a checksum'),
    re.compile('^Add constants'),
    re.compile('^Add sequence'),
    re.compile('^Add value fields changing sequence'),
    re.compile('^Add XML'),
    re.compile('^Aggregate Rows'),
    re.compile('^Agile '),
    re.compile('^Agile '),
    re.compile('^Analytic Query'),
    re.compile('^Append streams'),
    re.compile('^ARFF Output'),
    re.compile('^Automatic Documentation Output'),
    re.compile('^Avro input'),
    re.compile('^Block this step until steps finish'),
    re.compile('^Blocking Step'),
    re.compile('^Bulk loading '),
    re.compile('^Bulk loading'),
    re.compile('^Calculator'),
    re.compile('^Call DB Procedure'),
    re.compile('^Cassandra input'),
    re.compile('^Cassandra output'),
    re.compile('^Change file encoding'),
    re.compile('^Check if a column exists'),
    re.compile('^Check if file is locked'),
    re.compile('^Check if webservice is available'),
    re.compile('^Clone row'),
    re.compile('^Closure Generator'),
    re.compile('^Combination lookup/update'),
    re.compile('^Concat Fields'),
    re.compile('^Copy rows to result'),
    re.compile('^CouchDB Input'),
    re.compile('^Credit card validator'),
    re.compile('^CSV file input'),
    re.compile('^Data Grid'),
    re.compile('^Data Validator'),
    re.compile('^Database join'),
    re.compile('^Database lookup'),
    re.compile('^De-serialize from file'),
    re.compile('^Delay row'),
    re.compile('^Delete '),
    re.compile('^Delete'),
    re.compile('^Detect empty stream'),
    re.compile('^Dimension lookup/update'),
    re.compile('^Dummy (do nothing)'),
    re.compile('^Dynamic SQL row'),
    re.compile('^Edi to XML'),
    re.compile('^ElasticSearch Bulk Insert'),
    re.compile('^Email messages input'),
    re.compile('^ESRI Shapefile Reader'),
    re.compile('^ETL Metadata Injection'),
    re.compile('^Example plugin'),
    re.compile('^Execute a process'),
    re.compile('^Execute row SQL script'),
    re.compile('^Execute SQL script'),
    re.compile('^File exists'),
    re.compile('^Filter Rows'),
    re.compile('^Fixed file input'),
    re.compile('^Flow '),
    re.compile('^Formula'),
    re.compile('^Fuzzy match'),
    re.compile('^Generate random credit card numbers'),
    re.compile('^Generate random value'),
    re.compile('^Generate Rows'),
    re.compile('^Get data from XML'),
    re.compile('^Get File Names'),
    re.compile('^Get files from result'),
    re.compile('^Get Files Rows Count'),
    re.compile('^Get ID from slave server'),
    re.compile('^Get previous row fields'),
    re.compile('^Get repository names'),
    re.compile('^Get rows from result'),
    re.compile('^Get SubFolder names'),
    re.compile('^Get System Info'),
    re.compile('^Get table names'),
    re.compile('^Get Variables'),
    re.compile('^Google Analytics'),
    re.compile('^Google Docs Input'),
    re.compile('^GPLoad '),
    re.compile('^Greenplum Load '),
    re.compile('^Greenplum Load'),
    re.compile('^Group by'),
    re.compile('^GZIP CSV Input'),
    re.compile('^Hadoop File Input'),
    re.compile('^Hadoop File Output'),
    re.compile('^HBase input'),
    re.compile('^HBase output'),
    re.compile('^HBase Row Decoder'),
    re.compile('^HL7 Input'),
    re.compile('^HL7Input'),
    re.compile('^HTTP client'),
    re.compile('^HTTP Post'),
    re.compile('^IBM Websphere MQ Consumer'),
    re.compile('^IBM Websphere MQ Producer'),
    re.compile('^Identify last row in a stream'),
    re.compile('^If field value is null'),
    re.compile('^Infobright Loader'),
    re.compile('^Ingres VectorWise Bulk Loader'),
    re.compile('^Injector'),
    re.compile('^Input '),
    re.compile('^Input '),
    re.compile('^Input '),
    re.compile('^Input '),
    re.compile('^Input'),
    re.compile('^Input'),
    re.compile('^Input'),
    re.compile('^Insert / Update'),
    re.compile('^Java Filter'),
    re.compile('^JMS Consumer'),
    re.compile('^JMS Producer'),
    re.compile('^JmsInput'),
    re.compile('^JmsOutput '),
    re.compile('^Job Executor'),
    re.compile('^JobExecutor '),
    re.compile('^Join Rows (cartesian product) '),
    re.compile('^Joins'),
    re.compile('^Joins'),
    re.compile('^JSON Input'),
    re.compile('^JSON output'),
    re.compile('^Knowledge Flow'),
    re.compile('^Knowledge Flow'),
    re.compile('^LDAP Input'),
    re.compile('^LDAP Output'),
    re.compile('^LDIF Input'),
    re.compile('^Load file content in memory'),
    re.compile('^LucidDB Bulk Loader'),
    re.compile('^LucidDB Streaming Loader'),
    re.compile('^Mail Validator'),
    re.compile('^Mail'),
    re.compile('^Mapping '),
    re.compile('^Mapping (sub-transformation)'),
    re.compile('^Mapping input specification'),
    re.compile('^Mapping output specification'),
    re.compile('^MapReduce Input'),
    re.compile('^MapReduce Output'),
    re.compile('^MaxMind GeoIP Lookup'),
    re.compile('^Memory Group by'),
    re.compile('^Merge Join'),
    re.compile('^Merge Rows (diff)'),
    re.compile('^Metadata structure of stream'),
    re.compile('^Microsoft Access Input '),
    re.compile('^Microsoft Access Output'),
    re.compile('^Microsoft Excel Input'),
    re.compile('^Microsoft Excel Output'),
    re.compile('^Microsoft Excel Writer'),
    re.compile('^Modified Java Script Value'),
    re.compile('^Mondrian Input'),
    re.compile('^MonetDB Agile Mart'),
    re.compile('^MonetDB Bulk Loader'),
    re.compile('^MongoDB Input'),
    re.compile('^MongoDB Output'),
    re.compile('^MQInput'),
    re.compile('^MQOutput'),
    re.compile('^Multiway Merge Join'),
    re.compile('^MySQL Bulk Loader'),
    re.compile('^Null if...'),
    re.compile('^Number range'),
    re.compile('^OLAP Input'),
    re.compile('^opdts.jobexecutor.JobExecutorMeta '),
    re.compile('^OpenERP Object Delete'),
    re.compile('^OpenERP Object Input'),
    re.compile('^OpenERP Object Output'),
    re.compile('^OpenERPObjectDelete'),
    re.compile('^OpenERPObjectOutputImport'),
    re.compile('^Oracle Bulk Loader'),
    re.compile('^Output '),
    re.compile('^Output '),
    re.compile('^Output '),
    re.compile('^Output '),
    re.compile('^Output steps metrics'),
    re.compile('^Output'),
    re.compile('^Palo Cell Input'),
    re.compile('^Palo Cell Output'),
    re.compile('^Palo Dimension Input'),
    re.compile('^Palo Dimension Output'),
    re.compile('^PaloCellInput'),
    re.compile('^PaloCellOutput'),
    re.compile('^PaloDimInput'),
    re.compile('^PaloDimOutput'),
    re.compile('^Pentaho Reporting Output'),
    re.compile('^PostgreSQL Bulk Loader'),
    re.compile('^Prioritize streams'),
    re.compile('^Process files'),
    re.compile('^Properties Output'),
    re.compile('^Property Input'),
    re.compile('^R script executor'),
    re.compile('^Regex Evaluation'),
    re.compile('^Replace in string'),
    re.compile('^Reservoir Sampling'),
    re.compile('^REST Client'),
    re.compile('^Row denormaliser'),
    re.compile('^Row flattener'),
    re.compile('^Row Normaliser'),
    re.compile('^RSS Input'),
    re.compile('^RSS Output'),
    re.compile('^Rule Accumulator'),
    re.compile('^Rule Executor'),
    re.compile('^Run SSH commands'),
    re.compile('^S3 CSV Input'),
    re.compile('^S3 File Output'),
    re.compile('^Salesforce Delete'),
    re.compile('^Salesforce Input'),
    re.compile('^Salesforce Insert'),
    re.compile('^Salesforce Update'),
    re.compile('^Salesforce Upsert'),
    re.compile('^Sample rows'),
    re.compile('^SAP Input'),
    re.compile('^SAS Input'),
    re.compile('^Script'),
    re.compile('^Secret key generator'),
    re.compile('^Select values '),
    re.compile('^Send message to Syslog'),
    re.compile('^Send messages to a JMS server'),
    re.compile('^Serialize to file'),
    re.compile('^Set field value to a constant'),
    re.compile('^Set field value'),
    re.compile('^Set files in result'),
    re.compile('^Set Variables'),
    re.compile('^SFTP Put'),
    re.compile('^Simple Mapping'),
    re.compile('^SimpleMapping'),
    re.compile('^Single Threader'),
    re.compile('^Socket reader'),
    re.compile('^Socket writer'),
    re.compile('^Sort rows'),
    re.compile('^Sorted Merge '),
    re.compile('^Split field to rows'),
    re.compile('^Split Fields'),
    re.compile('^Splunk Input'),
    re.compile('^Splunk Output'),
    re.compile('^SQL File Output'),
    re.compile('^SSTable Output'),
    re.compile('^Statistics'),
    re.compile('^Stream lookup'),
    re.compile('^Streaming XML Input'),
    re.compile('^String operations'),
    re.compile('^Strings cut'),
    re.compile('^Switch / Case'),
    re.compile('^Symmetric Cryptography'),
    re.compile('^Synchronize after merge'),
    re.compile('^Table Agile Mart'),
    re.compile('^Table Compare'),
    re.compile('^Table exists'),
    re.compile('^Table input'),
    re.compile('^Table output '),
    re.compile('^TableCompare'),
    re.compile('^Teradata Fastload Bulk Loader'),
    re.compile('^Teradata TPT Insert Upsert Bulk Loader'),
    re.compile('^Text file input'),
    re.compile('^Text file output'),
    re.compile('^Transform'),
    re.compile('^Transformation Executor'),
    re.compile('^Unique rows (HashSet)'),
    re.compile('^Unique rows'),
    re.compile('^Univariate Statistics'),
    re.compile('^Update'),
    re.compile('^User Defined Java Class'),
    re.compile('^User Defined Java Expression'),
    re.compile('^Utility '),
    re.compile('^Value Mapper'),
    re.compile('^Vertica Bulk Loader'),
    re.compile('^Web services lookup'),
    re.compile('^Write to log '),
    re.compile('^XBase input'),
    re.compile('^XML Input Stream (StAX)'),
    re.compile('^XML Input'),
    re.compile('^XML Join'),
    re.compile('^XML Output'),
    re.compile('^XSD Validator'),
    re.compile('^XSL Transformation'),
    re.compile('^Yaml Input'),
    re.compile('^Zip File'),
    re.compile('^ZipFile'),
    re.compile('^Abort job'),
    re.compile('^Add filenames to result'),
    re.compile('^Amazon EMR Job Executor'),
    re.compile('^Amazon Hive Job Executor'),
    re.compile('^Big Data '),
    re.compile('^Big Data '),
    re.compile('^BulkLoad from Mysql into file'),
    re.compile('^BulkLoad into MSSQL'),
    re.compile('^BulkLoad into Mysql'),
    re.compile('^Check Db connections'),
    re.compile('^Check files locked'),
    re.compile('^Check if a folder is empty'),
    re.compile('^Check if connected to repository'),
    re.compile('^Check if XML file is well formed'),
    re.compile('^Check webservice availability'),
    re.compile('^Checks if files exist'),
    re.compile('^Columns exist in a table'),
    re.compile('^Compare folders'),
    re.compile('^Convert file between Windows and Unix'),
    re.compile('^Copy Files'),
    re.compile('^Copy or Move result filenames'),
    re.compile('^Create a folder'),
    re.compile('^Create file'),
    re.compile('^Decrypt files with PGP'),
    re.compile('^Delete file'),
    re.compile('^Delete filenames from result'),
    re.compile('^Delete files'),
    re.compile('^Delete folders'),
    re.compile('^Display Msgbox Info'),
    re.compile('^DTD Validator'),
    re.compile('^DUMMY (internal: SPECIAL) '),
    re.compile('^Dummy'),
    re.compile('^Encrypt files with PGP'),
    re.compile('^Evaluate files metrics'),
    re.compile('^Evaluate rows number in a table'),
    re.compile('^Example plugin'),
    re.compile('^Execute Hive jobs in Amazon EMR '),
    re.compile('^Execute MapReduce jobs in Amazon EMR '),
    re.compile('^Export repository to XML file'),
    re.compile('^File Compare'),
    re.compile('^File Exists'),
    re.compile('^FTP Delete'),
    re.compile('^General '),
    re.compile('^General '),
    re.compile('^Get a file with FTP'),
    re.compile('^Get a file with FTPS'),
    re.compile('^Get a file with SFTP'),
    re.compile('^Get mails (POP3/IMAP)'),
    re.compile('^Hadoop Copy Files'),
    re.compile('^Hadoop job executor'),
    re.compile('^HadoopJobExecutorPlugin'),
    re.compile('^HL7 MLLP Acknowledge'),
    re.compile('^HL7 MLLP Input'),
    re.compile('^HTTP'),
    re.compile('^JavaScript'),
    re.compile('^Job'),
    re.compile('^Mail validator'),
    re.compile('^Mail'),
    re.compile('^Move Files'),
    re.compile('^MS Access Bulk Load'),
    re.compile('^Oozie Job Executor'),
    re.compile('^opdje.copymoveresultfilenames.JobEntryCopyMoveResultFilenames'),
    re.compile('^opdje.palo.JobEntryCubeCreate'),
    re.compile('^opdje.palo.JobEntryCubeDelete'),
    re.compile('^opdje.sendnagiospassivecheck.JobEntrySendNagiosPassiveCheck'),
    re.compile('^opdje.sqoop.SqoopExportJobEntry'),
    re.compile('^opdje.sqoop.SqoopImportJobEntry '),
    re.compile('^opdje.ssh2get.JobEntrySSH2GET'),
    re.compile('^opdje.syslog.JobEntrySyslog'),
    re.compile('^opdjw.hadooptransjobexecutor.JobEntryHadoopTransJobExecutor '),
    re.compile('^org.pentaho.amazon.emr.job.AmazonElasticMapReduceJobExecutor'),
    re.compile('^org.pentaho.amazon.hive.job. AmazonHiveJobExecutor '),
    re.compile('^Palo '),
    re.compile('^Palo '),
    re.compile('^Palo Cube Create'),
    re.compile('^Palo Cube Delete'),
    re.compile('^PALO_CUBE_CREATE'),
    re.compile('^PALO_CUBE_DELETE'),
    re.compile('^Pentaho MapReduce'),
    re.compile('^Pig Script Executor'),
    re.compile('^Ping a host'),
    re.compile('^Process result filenames'),
    re.compile('^Put a file with FTP'),
    re.compile('^Put a file with SFTP'),
    re.compile('^Send information using Syslog'),
    re.compile('^Send Nagios passive check'),
    re.compile('^Send SNMP trap'),
    re.compile('^SEND_NAGIOS_PASSIVE_CHECK'),
    re.compile('^Set variables'),
    re.compile('^Shell'),
    re.compile('^Simple evaluation'),
    re.compile('^SQL'),
    re.compile('^Sqoop Export'),
    re.compile('^Sqoop Import'),
    re.compile('^SSH2 Get'),
    re.compile('^SSH2 Put'),
    re.compile('^START (internal: SPECIAL)'),
    re.compile('^Start a YARN Kettle Cluster'),
    re.compile('^Start'),
    re.compile('^Stop a YARN Kettle Cluster'),
    re.compile('^Stops a YARN Kettle Cluster'),
    re.compile('^Success'),
    re.compile('^Table exists'),
    re.compile('^Talend Job Execution'),
    re.compile('^Transformation'),
    re.compile('^Truncate tables'),
    re.compile('^Unzip file'),
    re.compile('^Upload files to FTPS'),
    re.compile('^Use the Dummy job entry to do nothing in a job.'),
    re.compile('^Utility '),
    re.compile('^Utility '),
    re.compile('^Utility '),
    re.compile('^Verify file signature with PGP'),
    re.compile('^Wait for file'),
    re.compile('^Wait for SQL'),
    re.compile('^Wait for'),
    re.compile('^Write to file'),
    re.compile('^Write To Log'),
    re.compile('^XSD Validator'),
    re.compile('^XSL Transformation'),
    re.compile('^Zip file')
]
